ansible_become_pass: ENC[AES256_GCM,data:6ggj0TE=,iv:L+vC2i04c8MGFLihsjs+qCsJ9EgI3gaErKXVlpd7Z+U=,tag:KR5KYuJwC+MM0lzZ10OxWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1td266h3akjy3a238jw5kwhpkwlyj54am3gjfg9hy62748wtxlflqtfx2pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaWQzZ1JwbGZQK2R1Wkoy
            Vjk1eHVkeHRrRzlrWnlvVGdxOUYvKy8vckdRCkUvMWVlQ1Z4a0V1aXBGZU1hQlox
            UTZydWcwN0I1M2hoK0taZkxuNWhxTWMKLS0tIDRhRkJyVjY3My9XczZsK3RscVhr
            ek1pbGIzYVBhZ3JOa2dqZDViLzBwTzQKEvd0Bj4rQtJXFJfC+SqnHksSVFxPFojA
            YOcuIXE2Nz2jbUUEGH7odgmQMdp3G7W3pe4gDqM7Vu4PoKIbCmu0iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T00:40:02Z"
    mac: ENC[AES256_GCM,data:nWY+77QYQvI/N4LYq2MzH1LV4vKmn04OsCk6Y70BjaP+M7DHS3rD8JAmolpMLIpOBRZwqLKRIbnjdgvH4vTXOnTSxmLOAplgUya7z6Nb0MIjiILvLvYBo6/yTh5u29ltZLWxFx1TaQOrLVS3ledeJZLUSTFn3ayHUfh1T5ABl/4=,iv:s4rkQirCEhxZCg6TMvvNRGzY7euZfiAG8ePGjL3dfSQ=,tag:/gEG4AXgnsqDi7vfBBXE/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
