ansible_become_pass: ENC[AES256_GCM,data:JWCusDM=,iv:KJGtaOyG+fprfVa/DQXD2KDrKv32bIKe7gKBwDWnZaw=,tag:MdMHZk2Bq5l5x39c1If2DA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1td266h3akjy3a238jw5kwhpkwlyj54am3gjfg9hy62748wtxlflqtfx2pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QUEvc1FmSlRXZTYySEZj
            ZjRHZW9pc1ExTkQ4YURaeVVlN2poRDUyMVVNCk1PM3VkRXBJMDJBL29tY2h1d2hR
            TEJTelorSEREUTNKeDJiZjlxd2RCd00KLS0tIEFqWmw4WkN0bUt2WktFUVhzL0Fq
            NUVVU3J2di9NdFM2eFVXY1NrdlJtVGsKSBdL5RdzZ4a3YZYuHhjUcbJFVmZufYMn
            OR8AWO8mWdrL7G/1EDLlwgKvsWBYyuIPGHPWEgs/Nq9R1BSBSikU1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T00:40:02Z"
    mac: ENC[AES256_GCM,data:cbNgg8ThzTBEjQrX2/G6iVXfDMKtYG1S82sr+9hEuyrGE9tSler7ovIfNJbP9xBB5L9m27cJ3lRQYNXWyhO9LNFVvwPqdFPle8WTr+OEM7bNY0Z8XC2ODjxJIaShsB6r/lOLqRNm96TVdwWH/xTMPHdTtWAMto98loRt9OpJL70=,iv:oZIm3iOliM6OsODvKt8eZn71z6g0QVDdcPSKN8a6Cxo=,tag:XEZhdzwtCvhsq7vm929tFg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
