apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qftPBk7nkBYAQjjPJPyAJK1v6TFwVf8a,iv:3KRO7t1JvvDuTrIcsIkbWySKFpsgPvWWiTt6gP2Ou1k=,tag:RlYd6M/qT6yDc+fj1oP+uw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1td266h3akjy3a238jw5kwhpkwlyj54am3gjfg9hy62748wtxlflqtfx2pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y0hBS1FrcHliYjA4cDNk
            dm1mVzYyTStxeDRqcC9mQTNVRU05ZFcvcVZjCmxiL2o5UUx0RUxINnd3TmorcmNl
            c0JuWktGU3NBK1cwcmtkc2xjWk00T2cKLS0tIDZVVzZBd3hHQ1RmMEVIT0NxaUVP
            aHllY2d6cXRDNUs3WE1JVnlCWHJVb2MK2TMgNNKvun/f4l7+opsJDgTI0ab+eut5
            7+JRUVHpDulY73Ew3462h8uzRH3rX6Jvkp0UmdQ961/nQhnCKEdh6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T00:40:35Z"
    mac: ENC[AES256_GCM,data:sHmzJUNfBuvUTdKvl714CXtfbUZOIF0aIZuUJfzMZgnFkeVHFCbzhBH2H9R31ZRNnUjw/KeaCOfmPFDItOWvSq4pUYzZY9bXwCZwjB31R2H84hVmX7iGRGtkBbfAmtJv8+jSVp5s1kxCpzaOEF1j32UqQUaaEQn4uOvnnz4u6Hc=,iv:BXd/BhMwtvyIctudgKewR8LfIuypENRNXVOA/BeUYmE=,tag:3VTafK1fZneWmjcev5qWrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
