apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:sYUwebyvlRDhKqGn,iv:e4saJbIPG1UE6ELEnHAOv7yPXYARekvPY/C/PVOYDno=,tag:VerDY5LJIaP+Zf6PCnoDrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1td266h3akjy3a238jw5kwhpkwlyj54am3gjfg9hy62748wtxlflqtfx2pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQmVmVHBTUkF1WlZxalBL
            WUI5N1U4UGhrZlZMVFo1dUNCVk94SklJNkJjCnd4bGV5MUVEWllacnV2TE14VU5C
            V1hSeXY4ZGJDRVFTdnY5RUd2bmkyekEKLS0tIHN0T2xRblVCaDU5cDZrQmwwUE5Y
            L2ZQbHRsM3NPUm5wRnV1SU5MMEtvQTgKLsBm9nM4wkw7dNL5A8EVGSttrzXgt2kl
            /S4qwUi1Qs5DIhgsx+SKkTi0NkQ7hGDi1Ra5kS1GsMuMZYaXGKuEKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T00:49:27Z"
    mac: ENC[AES256_GCM,data:blw4kv/IxG+timNvUP5aWJoRN2YSRC28wU+B76fVG2p19dMibDtBqncRF7ANor45/AAfPnij5mT4GvaWhBY8LpID9GONGFy2MNrVQbv7XbUIN/E2uiY4BTAs+nT+YaDtle82PQeNiIuawGPIODXzrjRsre01iADuVdx5v+PDuvM=,iv:XArsr8MXPog7W9NZ1WaSycws2xZfZheUSlSTQo7x8nI=,tag:WFT3s21MNPmC17TjZButfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
